# Build Stage
FROM node:20-bookworm as build
WORKDIR /app
COPY package.json .
RUN npm install
RUN npm install -D postcss@8 autoprefixer@10 tailwindcss@3.4.17
COPY . .
RUN npm run build

# Production Stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
