"""mvp_schema

Revision ID: 1d2b5d789c20
Revises: 
Create Date: 2026-01-04 09:45:24.636304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d2b5d789c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_id'), table_name='securities')
    op.drop_index(op.f('ix_securities_ticker'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('idx_bitemporal_lookup'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_security_ticker'), table_name='market_prices')
    op.drop_index(op.f('market_prices_valid_from_idx'), table_name='market_prices')
    op.drop_table('market_prices')
    op.add_column('price_history', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('price_history', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_price_history_is_current'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_temporal'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_transaction'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_transaction_from'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_transaction_to'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_valid_from'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_valid_to'), table_name='price_history')
    op.create_unique_constraint('uq_asset_date', 'price_history', ['asset_id', 'trade_date'])
    op.drop_column('price_history', 'transaction_to')
    op.drop_column('price_history', 'valid_from')
    op.drop_column('price_history', 'is_current')
    op.drop_column('price_history', 'valid_to')
    op.drop_column('price_history', 'transaction_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('transaction_from', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('price_history', sa.Column('valid_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('price_history', sa.Column('transaction_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_asset_date', 'price_history', type_='unique')
    op.create_index(op.f('ix_price_history_valid_to'), 'price_history', ['valid_to'], unique=False)
    op.create_index(op.f('ix_price_history_valid_from'), 'price_history', ['valid_from'], unique=False)
    op.create_index(op.f('ix_price_history_transaction_to'), 'price_history', ['transaction_to'], unique=False)
    op.create_index(op.f('ix_price_history_transaction_from'), 'price_history', ['transaction_from'], unique=False)
    op.create_index(op.f('ix_price_history_transaction'), 'price_history', ['transaction_from', 'transaction_to'], unique=False)
    op.create_index(op.f('ix_price_history_temporal'), 'price_history', ['asset_id', 'trade_date', 'valid_from', 'is_current'], unique=False)
    op.create_index(op.f('ix_price_history_is_current'), 'price_history', ['is_current'], unique=False)
    op.drop_column('price_history', 'updated_at')
    op.drop_column('price_history', 'created_at')
    op.create_table('market_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('security_ticker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('transaction_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transaction_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'valid_from', name=op.f('market_prices_pkey'))
    )
    op.create_index(op.f('market_prices_valid_from_idx'), 'market_prices', [sa.literal_column('valid_from DESC')], unique=False)
    op.create_index(op.f('ix_market_prices_security_ticker'), 'market_prices', ['security_ticker'], unique=False)
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('idx_bitemporal_lookup'), 'market_prices', ['security_ticker', 'valid_from', 'transaction_to'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), server_default=sa.text("'Stock'::character varying"), autoincrement=False, nullable=True),
    sa.Column('maturity_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('coupon_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('face_value', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('100.0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('securities_pkey'))
    )
    op.create_index(op.f('ix_securities_ticker'), 'securities', ['ticker'], unique=True)
    op.create_index(op.f('ix_securities_id'), 'securities', ['id'], unique=False)
    # ### end Alembic commands ###
